let suggestions = [
  "Select all content → Ctrl + A",
  "Copy selected items to clipboard → Ctrl + C (or Ctrl + Insert)",
  "Cut selected items to clipboard → Ctrl + X",
  "Paste content from clipboard → Ctrl + V (or Shift + Insert)",
  "Undo an action, including undelete files (limited) → Ctrl + Z",
  "Redo an action → Ctrl + Y",
  "Create new folder on desktop or File Explorer → Ctrl + Shift + N",
  "Close active window. (If no active window is present, a shutdown box appears.) → Alt + F4",
  "Delete selected item to the Recycle Bin → Ctrl + D (Del)",
  "Delete the selected item permanently, skipping Recycle Bin → Shift + Delete",
  "Rename selected item → F2",
  "Close current task → Esc",
  "Switch between open apps → Alt + Tab",
  "Take a screenshot and stores it in the clipboard → PrtScn",
  "Open Settings app → Windows key + I",
  "Open File Explorer → Windows key + E",
  "Open Action center → Windows key + A",
  "Display and hide the desktop → Windows key + D",
  "Lock device → Windows key + L",
  "Open Clipboard bin → Windows key + V",
  "Open emoji panel → Windows key + Period (.) or Semicolon (;)",
  "Capture a full screenshot in the 'Screenshots' folder → Windows key + PrtScn",
  "Capture part of the screen with Snip & Sketch → Windows key + Shift + S",
  "Snap app or window left → Windows key + Left arrow key",
  "Snap app or window right → Windows key + Right arrow key",
];
